version: "4"
services:
  System:
    build: .
    environment:
      API_ID_KEY: $API_ID_KEY
      API_HASH_KEY: $API_HASH_KEY
      STRING_SESSION: $STRING_SESSION
      Skynet: $Skynet
      ENFORCERS: $ENFORCERS
      Skynet_logs: $Skynet_logs
      Skynet_approved_logs: $Skynet_approved_logs
      GBAN_MSG_LOGS: $GBAN_MSG_LOGS
